# Script to add 3000 to all IDs in CLUBS_COUNTRY_TEAMS list


CLUBS_COUNTRY_TEAMS = [
    (2000, 'Iceland', 'Iceland', 'country', None, 'ISL', None, None, None, None),
    (2001, 'Afghanistan', 'Afghanistan', 'country', None, 'AFG', None, None, None, None),
    (2002, 'Albania', 'Albania', 'country', None, 'ALB', None, None, None, None),
    (2003, 'Algeria', 'Algeria', 'country', None, 'DZA', None, None, None, None),
    (2004, 'Andorra', 'Andorra', 'country', None, 'AND', None, None, None, None),
    (2005, 'Angola', 'Angola', 'country', None, 'AGO', None, None, None, None),
    (2006, 'Antigua and Barbuda', 'Antigua and Barbuda', 'country', None, 'ATG', None, None, None, None),
    (2007, 'Argentina', 'Argentina', 'country', None, 'ARG', None, None, None, None),
    (2008, 'Armenia', 'Armenia', 'country', None, 'ARM', None, None, None, None),
    (2009, 'Australia', 'Australia', 'country', None, 'AUS', None, None, None, None),
    (2010, 'Austria', 'Austria', 'country', None, 'AUT', None, None, None, None),
    (2011, 'Azerbaijan', 'Azerbaijan', 'country', None, 'AZE', None, None, None, None),
    (2012, 'Bahamas', 'Bahamas', 'country', None, 'BHS', None, None, None, None),
    (2013, 'Bahrain', 'Bahrain', 'country', None, 'BHR', None, None, None, None),
    (2014, 'Bangladesh', 'Bangladesh', 'country', None, 'BGD', None, None, None, None),
    (2015, 'Barbados', 'Barbados', 'country', None, 'BRB', None, None, None, None),
    (2016, 'Belarus', 'Belarus', 'country', None, 'BLR', None, None, None, None),
    (2017, 'Belgium', 'Belgium', 'country', None, 'BEL', None, None, None, None),
    (2018, 'Belize', 'Belize', 'country', None, 'BLZ', None, None, None, None),
    (2019, 'Benin', 'Benin', 'country', None, 'BEN', None, None, None, None),
    (2020, 'Bhutan', 'Bhutan', 'country', None, 'BTN', None, None, None, None),
    (2021, 'Bolivia', 'Bolivia', 'country', None, 'BOL', None, None, None, None),
    (2022, 'Bosnia and Herzegovina', 'Bosnia and Herzegovina', 'country', None, 'BIH', None, None, None, None),
    (2023, 'Botswana', 'Botswana', 'country', None, 'BWA', None, None, None, None),
    (2024, 'Brazil', 'Brazil', 'country', None, 'BRA', None, None, None, None),
    (2025, 'Brunei Darussalam', 'Brunei Darussalam', 'country', None, 'BRN', None, None, None, None),
    (2026, 'Bulgaria', 'Bulgaria', 'country', None, 'BGR', None, None, None, None),
    (2027, 'Burkina Faso', 'Burkina Faso', 'country', None, 'BFA', None, None, None, None),
    (2028, 'Burundi', 'Burundi', 'country', None, 'BDI', None, None, None, None),
    (2029, 'Cabo Verde', 'Cabo Verde', 'country', None, 'CPV', None, None, None, None),
    (2030, 'Cambodia', 'Cambodia', 'country', None, 'KHM', None, None, None, None),
    (2031, 'Cameroon', 'Cameroon', 'country', None, 'CMR', None, None, None, None),
    (2032, 'Canada', 'Canada', 'country', None, 'CAN', None, None, None, None),
    (2033, 'Central African Republic', 'Central African Republic', 'country', None, 'CAF', None, None, None, None),
    (2034, 'Chad', 'Chad', 'country', None, 'TCD', None, None, None, None),
    (2035, 'Chile', 'Chile', 'country', None, 'CHL', None, None, None, None),
    (2036, 'China', 'China', 'country', None, 'CHN', None, None, None, None),
    (2037, 'Colombia', 'Colombia', 'country', None, 'COL', None, None, None, None),
    (2038, 'Comoros', 'Comoros', 'country', None, 'COM', None, None, None, None),
    (2039, 'Congo', 'Congo', 'country', None, 'COG', None, None, None, None),
    (2040, 'Costa Rica', 'Costa Rica', 'country', None, 'CRI', None, None, None, None),
    (2041, 'Croatia', 'Croatia', 'country', None, 'HRV', None, None, None, None),
    (2042, 'Cuba', 'Cuba', 'country', None, 'CUB', None, None, None, None),
    (2043, 'Cyprus', 'Cyprus', 'country', None, 'CYP', None, None, None, None),
    (2044, 'Czech Republic', 'Czech Republic', 'country', None, 'CZE', None, None, None, None),
    (2045, 'Democratic Republic of the Congo', 'Democratic Republic of the Congo', 'country', None, 'COD', None, None, None, None),
    (2046, 'Denmark', 'Denmark', 'country', None, 'DNK', None, None, None, None),
    (2047, 'Djibouti', 'Djibouti', 'country', None, 'DJI', None, None, None, None),
    (2048, 'Dominica', 'Dominica', 'country', None, 'DMA', None, None, None, None),
    (2049, 'Dominican Republic', 'Dominican Republic', 'country', None, 'DOM', None, None, None, None),
    (2050, 'Ecuador', 'Ecuador', 'country', None, 'ECU', None, None, None, None),
    (2051, 'Egypt', 'Egypt', 'country', None, 'EGY', None, None, None, None),
    (2052, 'El Salvador', 'El Salvador', 'country', None, 'SLV', None, None, None, None),
    (2053, 'Equatorial Guinea', 'Equatorial Guinea', 'country', None, 'GNQ', None, None, None, None),
    (2054, 'Eritrea', 'Eritrea', 'country', None, 'ERI', None, None, None, None),
    (2055, 'Estonia', 'Estonia', 'country', None, 'EST', None, None, None, None),
    (2056, 'Eswatini', 'Eswatini', 'country', None, 'SWZ', None, None, None, None),
    (2057, 'Ethiopia', 'Ethiopia', 'country', None, 'ETH', None, None, None, None),
    (2058, 'Fiji', 'Fiji', 'country', None, 'FJI', None, None, None, None),
    (2059, 'Finland', 'Finland', 'country', None, 'FIN', None, None, None, None),
    (2060, 'France', 'France', 'country', None, 'FRA', None, None, None, None),
    (2061, 'Gabon', 'Gabon', 'country', None, 'GAB', None, None, None, None),
    (2062, 'Gambia', 'Gambia', 'country', None, 'GMB', None, None, None, None),
    (2063, 'Georgia', 'Georgia', 'country', None, 'GEO', None, None, None, None),
    (2064, 'Germany', 'Germany', 'country', None, 'DEU', None, None, None, None),
    (2065, 'Ghana', 'Ghana', 'country', None, 'GHA', None, None, None, None),
    (2066, 'Greece', 'Greece', 'country', None, 'GRC', None, None, None, None),
    (2067, 'Grenada', 'Grenada', 'country', None, 'GRD', None, None, None, None),
    (2068, 'Guatemala', 'Guatemala', 'country', None, 'GTM', None, None, None, None),
    (2069, 'Guinea', 'Guinea', 'country', None, 'GIN', None, None, None, None),
    (2070, 'Guinea-Bissau', 'Guinea-Bissau', 'country', None, 'GNB', None, None, None, None),
    (2071, 'Guyana', 'Guyana', 'country', None, 'GUY', None, None, None, None),
    (2072, 'Haiti', 'Haiti', 'country', None, 'HTI', None, None, None, None),
    (2073, 'Honduras', 'Honduras', 'country', None, 'HND', None, None, None, None),
    (2074, 'Hungary', 'Hungary', 'country', None, 'HUN', None, None, None, None),
    (2075, 'India', 'India', 'country', None, 'IND', None, None, None, None),
    (2076, 'Indonesia', 'Indonesia', 'country', None, 'IDN', None, None, None, None),
    (2077, 'Iran', 'Iran', 'country', None, 'IRN', None, None, None, None),
    (2078, 'Iraq', 'Iraq', 'country', None, 'IRQ', None, None, None, None),
    (2079, 'Ireland', 'Ireland', 'country', None, 'IRL', None, None, None, None),
    (2080, 'Israel', 'Israel', 'country', None, 'ISR', None, None, None, None),
    (2081, 'Italy', 'Italy', 'country', None, 'ITA', None, None, None, None),
    (2082, 'Jamaica', 'Jamaica', 'country', None, 'JAM', None, None, None, None),
    (2083, 'Japan', 'Japan', 'country', None, 'JPN', None, None, None, None),
    (2084, 'Jordan', 'Jordan', 'country', None, 'JOR', None, None, None, None),
    (2085, 'Kazakhstan', 'Kazakhstan', 'country', None, 'KAZ', None, None, None, None),
    (2086, 'Kenya', 'Kenya', 'country', None, 'KEN', None, None, None, None),
    (2087, 'Kiribati', 'Kiribati', 'country', None, 'KIR', None, None, None, None),
    (2088, 'Kuwait', 'Kuwait', 'country', None, 'KWT', None, None, None, None),
    (2089, 'Kyrgyzstan', 'Kyrgyzstan', 'country', None, 'KGZ', None, None, None, None),
    (2090, 'Laos', 'Laos', 'country', None, 'LAO', None, None, None, None),
    (2091, 'Latvia', 'Latvia', 'country', None, 'LVA', None, None, None, None),
    (2092, 'Lebanon', 'Lebanon', 'country', None, 'LBN', None, None, None, None),
    (2093, 'Lesotho', 'Lesotho', 'country', None, 'LSO', None, None, None, None),
    (2094, 'Liberia', 'Liberia', 'country', None, 'LBR', None, None, None, None),
    (2095, 'Libya', 'Libya', 'country', None, 'LBY', None, None, None, None),
    (2096, 'Liechtenstein', 'Liechtenstein', 'country', None, 'LIE', None, None, None, None),
    (2097, 'Lithuania', 'Lithuania', 'country', None, 'LTU', None, None, None, None),
    (2098, 'Luxembourg', 'Luxembourg', 'country', None, 'LUX', None, None, None, None),
    (2099, 'Madagascar', 'Madagascar', 'country', None, 'MDG', None, None, None, None),
    (2100, 'Malawi', 'Malawi', 'country', None, 'MWI', None, None, None, None),
    (2101, 'Malaysia', 'Malaysia', 'country', None, 'MYS', None, None, None, None),
    (2102, 'Maldives', 'Maldives', 'country', None, 'MDV', None, None, None, None),
    (2103, 'Mali', 'Mali', 'country', None, 'MLI', None, None, None, None),
    (2104, 'Malta', 'Malta', 'country', None, 'MLT', None, None, None, None),
    (2105, 'Marshall Islands', 'Marshall Islands', 'country', None, 'MHL', None, None, None, None),
    (2106, 'Mauritania', 'Mauritania', 'country', None, 'MRT', None, None, None, None),
    (2107, 'Mauritius', 'Mauritius', 'country', None, 'MUS', None, None, None, None),
    (2108, 'Mexico', 'Mexico', 'country', None, 'MEX', None, None, None, None),
    (2109, 'Micronesia', 'Micronesia', 'country', None, 'FSM', None, None, None, None),
    (2110, 'Moldova', 'Moldova', 'country', None, 'MDA', None, None, None, None),
    (2111, 'Monaco', 'Monaco', 'country', None, 'MCO', None, None, None, None),
    (2112, 'Mongolia', 'Mongolia', 'country', None, 'MNG', None, None, None, None),
    (2113, 'Montenegro', 'Montenegro', 'country', None, 'MNE', None, None, None, None),
    (2114, 'Morocco', 'Morocco', 'country', None, 'MAR', None, None, None, None),
    (2115, 'Mozambique', 'Mozambique', 'country', None, 'MOZ', None, None, None, None),
    (2116, 'Myanmar', 'Myanmar', 'country', None, 'MMR', None, None, None, None),
    (2117, 'Namibia', 'Namibia', 'country', None, 'NAM', None, None, None, None),
    (2118, 'Nauru', 'Nauru', 'country', None, 'NRU', None, None, None, None),
    (2119, 'Nepal', 'Nepal', 'country', None, 'NPL', None, None, None, None),
    (2120, 'Netherlands', 'Netherlands', 'country', None, 'NLD', None, None, None, None),
    (2121, 'New Zealand', 'New Zealand', 'country', None, 'NZL', None, None, None, None),
    (2122, 'Nicaragua', 'Nicaragua', 'country', None, 'NIC', None, None, None, None),
    (2123, 'Niger', 'Niger', 'country', None, 'NER', None, None, None, None),
    (2124, 'Nigeria', 'Nigeria', 'country', None, 'NGA', None, None, None, None),
    (2125, 'North Korea', 'North Korea', 'country', None, 'PRK', None, None, None, None),
    (2126, 'North Macedonia', 'North Macedonia', 'country', None, 'MKD', None, None, None, None),
    (2127, 'Norway', 'Norway', 'country', None, 'NOR', None, None, None, None),
    (2128, 'Oman', 'Oman', 'country', None, 'OMN', None, None, None, None),
    (2129, 'Pakistan', 'Pakistan', 'country', None, 'PAK', None, None, None, None),
    (2130, 'Palau', 'Palau', 'country', None, 'PLW', None, None, None, None),
    (2131, 'Panama', 'Panama', 'country', None, 'PAN', None, None, None, None),
    (2132, 'Papua New Guinea', 'Papua New Guinea', 'country', None, 'PNG', None, None, None, None),
    (2133, 'Paraguay', 'Paraguay', 'country', None, 'PRY', None, None, None, None),
    (2134, 'Peru', 'Peru', 'country', None, 'PER', None, None, None, None),
    (2135, 'Philippines', 'Philippines', 'country', None, 'PHL', None, None, None, None),
    (2136, 'Poland', 'Poland', 'country', None, 'POL', None, None, None, None),
    (2137, 'Portugal', 'Portugal', 'country', None, 'PRT', None, None, None, None),
    (2138, 'Qatar', 'Qatar', 'country', None, 'QAT', None, None, None, None),
    (2139, 'Romania', 'Romania', 'country', None, 'ROU', None, None, None, None),
    (2140, 'Russia', 'Russia', 'country', None, 'RUS', None, None, None, None),
    (2141, 'Rwanda', 'Rwanda', 'country', None, 'RWA', None, None, None, None),
    (2142, 'Saint Kitts and Nevis', 'Saint Kitts and Nevis', 'country', None, 'KNA', None, None, None, None),
    (2143, 'Saint Lucia', 'Saint Lucia', 'country', None, 'LCA', None, None, None, None),
    (2144, 'Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines', 'country', None, 'VCT', None, None, None, None),
    (2145, 'Samoa', 'Samoa', 'country', None, 'WSM', None, None, None, None),
    (2146, 'San Marino', 'San Marino', 'country', None, 'SMR', None, None, None, None),
    (2147, 'Sao Tome and Principe', 'Sao Tome and Principe', 'country', None, 'STP', None, None, None, None),
    (2148, 'Saudi Arabia', 'Saudi Arabia', 'country', None, 'SAU', None, None, None, None),
    (2149, 'Senegal', 'Senegal', 'country', None, 'SEN', None, None, None, None),
    (2150, 'Serbia', 'Serbia', 'country', None, 'SRB', None, None, None, None),
    (2151, 'Seychelles', 'Seychelles', 'country', None, 'SYC', None, None, None, None),
    (2152, 'Sierra Leone', 'Sierra Leone', 'country', None, 'SLE', None, None, None, None),
    (2153, 'Singapore', 'Singapore', 'country', None, 'SGP', None, None, None, None),
    (2154, 'Slovakia', 'Slovakia', 'country', None, 'SVK', None, None, None, None),
    (2155, 'Slovenia', 'Slovenia', 'country', None, 'SVN', None, None, None, None),
    (2156, 'Solomon Islands', 'Solomon Islands', 'country', None, 'SLB', None, None, None, None),
    (2157, 'Somalia', 'Somalia', 'country', None, 'SOM', None, None, None, None),
    (2158, 'South Africa', 'South Africa', 'country', None, 'ZAF', None, None, None, None),
    (2159, 'South Korea', 'South Korea', 'country', None, 'KOR', None, None, None, None),
    (2160, 'South Sudan', 'South Sudan', 'country', None, 'SSD', None, None, None, None),
    (2161, 'Spain', 'Spain', 'country', None, 'ESP', None, None, None, None),
    (2162, 'Sri Lanka', 'Sri Lanka', 'country', None, 'LKA', None, None, None, None),
    (2163, 'Sudan', 'Sudan', 'country', None, 'SDN', None, None, None, None),
    (2164, 'Suriname', 'Suriname', 'country', None, 'SUR', None, None, None, None),
    (2165, 'Sweden', 'Sweden', 'country', None, 'SWE', None, None, None, None),
    (2166, 'Switzerland', 'Switzerland', 'country', None, 'CHE', None, None, None, None),
    (2167, 'Syria', 'Syria', 'country', None, 'SYR', None, None, None, None),
    (2168, 'Tajikistan', 'Tajikistan', 'country', None, 'TJK', None, None, None, None),
    (2169, 'Tanzania', 'Tanzania', 'country', None, 'TZA', None, None, None, None),
    (2170, 'Thailand', 'Thailand', 'country', None, 'THA', None, None, None, None),
    (2171, 'Timor-Leste', 'Timor-Leste', 'country', None, 'TLS', None, None, None, None),
    (2172, 'Togo', 'Togo', 'country', None, 'TGO', None, None, None, None),
    (2173, 'Tonga', 'Tonga', 'country', None, 'TON', None, None, None, None),
    (2174, 'Trinidad and Tobago', 'Trinidad and Tobago', 'country', None, 'TTO', None, None, None, None),
    (2175, 'Tunisia', 'Tunisia', 'country', None, 'TUN', None, None, None, None),
    (2176, 'Turkey', 'Turkey', 'country', None, 'TUR', None, None, None, None),
    (2177, 'Turkmenistan', 'Turkmenistan', 'country', None, 'TKM', None, None, None, None),
    (2178, 'Tuvalu', 'Tuvalu', 'country', None, 'TUV', None, None, None, None),
    (2179, 'Uganda', 'Uganda', 'country', None, 'UGA', None, None, None, None),
    (2180, 'Ukraine', 'Ukraine', 'country', None, 'UKR', None, None, None, None),
    (2181, 'United Arab Emirates', 'United Arab Emirates', 'country', None, 'ARE', None, None, None, None),
    (2182, 'United Kingdom', 'United Kingdom', 'country', None, 'GBR', None, None, None, None),
    (2183, 'United States', 'United States', 'country', None, 'USA', None, None, None, None),
    (2184, 'Uruguay', 'Uruguay', 'country', None, 'URY', None, None, None, None),
    (2185, 'Uzbekistan', 'Uzbekistan', 'country', None, 'UZB', None, None, None, None),
    (2186, 'Vanuatu', 'Vanuatu', 'country', None, 'VUT', None, None, None, None),
    (2187, 'Venezuela', 'Venezuela', 'country', None, 'VEN', None, None, None, None),
    (2188, 'Vietnam', 'Vietnam', 'country', None, 'VNM', None, None, None, None),
    (2189, 'Yemen', 'Yemen', 'country', None, 'YEM', None, None, None, None),
    (2190, 'Zambia', 'Zambia', 'country', None, 'ZMB', None, None, None, None),
    (2191, 'Zimbabwe', 'Zimbabwe', 'country', None, 'ZWE', None, None, None, None),
    (2192, 'Chinese Taipei', 'Chinese Taipei', 'country', None, 'TWN', None, None, None, None),
    (2193, 'Hong Kong', 'Hong Kong', 'country', None, 'HKG', None, None, None, None),
    (2194, 'Puerto Rico', 'Puerto Rico', 'country', None, 'PRI', None, None, None, None)
]

# Add 3000 to each ID
updated_clubs = [(club[0] + 3000, *club[1:]) for club in CLUBS_COUNTRY_TEAMS]

# Output the updated list
print('CLUBS_COUNTRY_TEAMS = [')
for club in updated_clubs:
    print(f'    {club},')
print(']')

# Optionally, save to a file
with open('updated_clubs_country_teams.py', 'w', encoding='utf-8') as f:
    f.write('CLUBS_COUNTRY_TEAMS = [\n')
    for club in updated_clubs:
        f.write(f'    {club},\n')
    f.write(']\n')

print("\nUpdated list saved to 'updated_clubs_country_teams.py'")